// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatbotController from "./chatbot_controller"
application.register("chatbot", ChatbotController)

import InlineEditorController from "./inline_editor_controller"
application.register("inline-editor", InlineEditorController)

import ProsemirrorController from "./prosemirror_controller"
application.register("prosemirror", ProsemirrorController)

import UiFeedbackController from "./ui_feedback_controller"
application.register("ui-feedback", UiFeedbackController)
