// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import InlineProsemirrorController from "./inline_prosemirror_controller"
application.register("inline-prosemirror", InlineProsemirrorController)

import UiFeedbackController from "./ui_feedback_controller"
application.register("ui-feedback", UiFeedbackController)
