name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - id: setup-chrome
        uses: browser-actions/setup-chrome@2e1d749697dd1612b833dba4a722266286fbefcd
        with:
          chrome-version: stable
      - run: ${{ steps.setup-chrome.outputs.chrome-path }} --version
      - name: Fix GA Chrome Permissions
        run: |
          sudo chown root:root ${{ steps.setup-chrome.outputs.chrome-path }}
          sudo chmod 4755 ${{ steps.setup-chrome.outputs.chrome-path }}
      
      - name: db:prepare
        env:
          RAILS_ENV: test
        run: bin/rails db:test:prepare db:seed

      - run: bin/rails test:system
        env:
          BROWSER_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

      # - run: bin/importmap audit

      - name: Lint code for consistent style
        run: bin/rubocop -f github

      - name: Run tests
        run: bin/rails test

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
